### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lhyxyw** [feria-tu/STFT-TCAN-A-TCN-Attention-based-Multivariate-Time-Series-Anomaly-Detection-Architecture#1]
Sir, could u share your dataset in the project?

Thanks!

**Comment by feria-tu** [comment]
I've updated the README, where I shared how to get the datasets used in the project.

**Comment by lhyxyw** [comment]
Thanks！
But, in the README,There is no main file in it.
Could u update the files?
Best Wishes!
